### ISSUE TITLE
GND missing schema information?

### ISSUE THREAD

**Issue by reckart** [zbw/sparql-queries#2]
Is it possible that the data behind the endpoint `http://zbw.eu/beta/sparql/gnd/query` was recently updated / reloaded and that during this process the base schema (https://d-nb.info/standards/elementset/gnd) information has not been loaded?

It seems that the data now only contains instances but e.g. the following query returns no information about the class:

```
PREFIX  gndo:   <http://d-nb.info/standards/elementset/gnd#>
PREFIX  text:   <http://jena.apache.org/text#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
#
select ?p ?o where {
  gndo:DifferentiatedPerson ?p ?o .
}
```

Some time back in June, it seems we were still able to access the schema information - cf. the screenshot under the following issue:

https://github.com/inception-project/inception/issues/299#issuecomment-425905765

**Comment by jneubert** [comment]
Yes, the dataset was updated early in August, with the June version of the GND dump files (unfortunately, the GND dump files do not contain version or last modified information, so reloads are not traceable for users of the endpoint).

Since we just load the dump files (after utf8 normalization) and supplement them only only by http://d-nb.info/standards/vocab/gnd/gnd-sc.rdf, I cannot tell about the missing gndo schema information. It would be easy to add also schema information, but that would be better provided upstream (to have it  in sync with the data itself). Perhaps @jentschk has ideas about that?

**Comment by ghost** [comment]
Do I understand correctly that you'd consider it helpful if the GND Ontology was added to the GND RDF dumps?  If so, I can certainly take this requirement. Some reference or explanation about why this is good/common practice would be helpful when it comes to prioritising. (Advanced warning: It might not be as easy to get as it might seem - which can also be derived from the fact that we weren't able to attach gnd-sc yet - which has been a long-standing wish from @jneubert :-/ )

What I don't understand is what the explanation for @reckart 's observation about ZBW's endpoint is. I'm pretty sure that our dumps haven't changed.

**Comment by reckart** [comment]
@jentschk we are building [a text annotation tool](https://inception-project.github.io) with the capability to use RDF-based resources as normative knowledge bases. For that, we search the web for interesting SPARQL endpoints and try out if and how we can map their contents to our user interface. So we look for some kind of hierarchical structure in the resource (usually a class hierarchy) and for instances of these classes and then we show them in our UI. Some time back, we were able to take the following screenshot (ignore the red boxes - the screenshot is being used out-of-context here):

![](https://user-images.githubusercontent.com/1410238/41506706-2f478124-7223-11e8-97d4-99f952cc9b69.png)

If I am not mistaken, the tree on the left shows the class hierarchy from the GND schema. 

Now, the last time we came back to testing against the ZBW GND SPARQL endpoint, we were no longer able to extract this hierarchy. I entered some queries manually into the SPARQL form and discovered, that there seem to be only instances in there, but not schema at all. Nowadays, we can only extract a flat list of instances. So right now, the best we can get out of the ZBW GND SPARQL endpoint is this:

<img width="1020" alt="2018-10-11_10-10-31" src="https://user-images.githubusercontent.com/1410238/46793575-fa400980-cd3d-11e8-9d25-3a521189bb70.png">

The first screenshot shows that having the schema information available allows generating a much more user-friendly access to the resource than if the schema is not available (as see in the second screenshot):

* with the schema, we can show the hierarchical structure
* with the schema, we can show which properties are available and display nicer human-readable names

**Comment by ghost** [comment]
Thank you for sharing your use of the data! Very interesting for us. 

My not-understanding was rather referring to the reason that caused what you observed - which possibly @jneubert can give. As I said, I don't believe anything changed at our end.

**Comment by jneubert** [comment]
Well, the `http://zbw.eu/beta/sparql/gnd/query` endpoint is, as the [doc](http://zbw.eu/beta/sparql-lab/about/) says, experimental. It is possible that I've loaded the gnd ontology manually at some point in time, which could explain your observation.

**Comment by reckart** [comment]
So - any conclusions? Assuming that the usefulness of having the ontology available in the SPARQL endpoint has been established ...

* ... should the ontology be included in the upstream dataset?
* ... or just be loaded into the SPARQL endpoint?

**Comment by jneubert** [comment]
Other use case/request by MisterSynergy at https://www.wikidata.org/wiki/User_talk:Jneubert#open_questions - that tipps the balance.

**Comment by jneubert** [comment]
Loaded https://d-nb.info/standards/elementset/gnd2018-05-15.ttl, which probably was in effect when the 1806 version of the GND dataset was created.

**Comment by jneubert** [comment]
Loaded https://d-nb.info/standards/elementset/gnd2018-05-15.ttl, which probably was in effect when the 1806 version of the GND dataset was created.

**Comment by reckart** [comment]
@jneubert is it possible that the GND ontology has again gone missing from the SPARQL endpoint?

**Comment by jneubert** [comment]
@reckart Should not have happened, but I've reloaded with the new 2018-10 version of the GND dump and the recent gndo.ttl.
